apiVersion: v1
kind: Pod
metadata:
  name: kafka-test
  namespace: kafka
spec:
  containers:
    - name: tester
      image: python:3.10
      command: ["sh", "-c"]
      args:
        - pip install kafka-python && sleep 3600

