apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: kafka
spec:
  clusterIP: None   # headless service
  ports:
    - port: 9092
      name: kafka
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: kafka
spec:
  serviceName: kafka
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.5.0
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper.kafka.svc.cluster.local:2181"

            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:9092"

            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://$(HOSTNAME).kafka.kafka.svc.cluster.local:9092"

            - name: KAFKA_BROKER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "3"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "3"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "2"

          command:
            - sh
            - -c
            - |
              export KAFKA_BROKER_ID=$(echo ${HOSTNAME} | awk -F'-' '{print $NF}')
              echo "Kafka broker ID=${KAFKA_BROKER_ID}"
              /etc/confluent/docker/run

          ports:
            - containerPort: 9092
          volumeMounts:
            - name: kafka-storage
              mountPath: /var/lib/kafka/data
  volumeClaimTemplates:
    - metadata:
        name: kafka-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

