apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: kafka
spec:
  ports:
    - name: client
      port: 2181
      targetPort: 2181
  selector:
    app: zookeeper

---
apiVersion: v1
kind: Pod
metadata:
  name: zookeeper
  namespace: kafka
  labels:
    app: zookeeper
spec:
  containers:
    - name: zookeeper
      image: confluentinc/cp-zookeeper:7.5.0
      env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
      ports:
        - containerPort: 2181

